### ISSUE TITLE
react-routerでリロードすると404エラーが出る問題

### ISSUE THREAD

**Issue by azujuuuuuun** [azujuuuuuun/markdown-editor#30]
サーバーでindex.htmlしか返していないから
/loginでindex.htmlを返したい

**Comment by zurajacoco** [comment]
任意のurlに対してindex.html（文字列）を返してjsをフロント側で展開
定義していないurlに404 not found を返すようにしたい

**Comment by azujuuuuuun** [comment]
上の実装だと404 not found を返せないので、定義していないurlにはクライアント側でNotFoundコンポーネントを出すようにする
